### ISSUE TITLE
no XC-3 support

### ISSUE THREAD

**Issue by ozel** [xcore/sc_ethernet#6]
what's the reason for not supporting the dual ethernet board XC-3 with this module?
I see ethernet_server_two_port() and phy_init_two_port() in the code, but they are disabled.

**Comment by DavidNorman** [comment]
Hi,

the reason is nothing more than the requirement to get the open source version of the high priority queueing code out quickly.    we will be working on fixing this issue when we have a bit of spare time (sadly we are a bit loaded at the moment).

sorry for that.

i have an AVB release to occupy me for the next 4 weeks, but after that I will be moving on to patching up holes in the ethernet and tcpip.   feel free to contribute a fix though, if you have one :)

**Comment by interactive-matter** [comment]
I am porting this to XC-3 (ap_led_tile) can I somehow help to get this issue resolved?

**Comment by DavidNorman** [comment]
Sorry. the issue is now resolved.  you should be able to define the following in ethernet_conf.h

#define NUM_ETHERNET_PORTS (2)

and if you do not want inter-port ethernet forwarding, then you can also define DISABLE_ETHERNET_PORT_FORWARDING which will prevent this.

see the app_bridge for an example which does nothing but fowards packets between the two sides of the device.

note that xtcp has not been extended to support multiple ports yet.  that would require the ARP table to be extended to have a 'port number' of the ARP reply, and to have this used when deciding which port to transmit a datagram through.

**Comment by interactive-matter** [comment]
from the source it looked closed - will test it next week - let'S see if I get packages through the XC-3 ;)

**Comment by DavidNorman** [comment]
note that the app_bridge defines XC-3 as the target hardware in the Makefile.  The source code defines either the one or two port top level ethernet server, so you will need to modifiy your top level main when you define the number of ports as more than one.

**Comment by DavidNorman** [comment]
I think that this is probably closed now?

**Comment by ozel** [comment]
for the records: I tested the throughput of broadcasts from one port to the other to be at 99% of 100Mbit which is very nice. receiving unicast frames over a channel from the server component (and not doing anything with it, just like in app_bridge) was possible up to 50Mbit. At higher rates something locks up in the stack. I think it's the same problem I have with just one port und receiving bursts of big packets. Sometimes sc_ethernet locks up and halts the chip (sometimes with runtime exceptions, at other times without). That btw. was the reason I was curious about the new HW locks, because I thought it could improve this behaviour.

**Comment by interactive-matter** [comment]
yes, sorry for the late reply. Was a bit busy.
I am on the way using it on the led tile kit on XC3. Not completely migrated the source but at least it compiles & looks good
