### ISSUE TITLE
smi_config in module_ethernet/src/server/smi.h is superfluous?

### ISSUE THREAD

**Issue by henkmuller** [xcore/sc_ethernet#9]
I don't think it is defined anywhere anymore.

**Comment by DavidNorman** [comment]
It's quite possible. It should probably be used in ethernet_server.xc, because the phy_init function ought to be calling the smi functions. 

As I discovered while I was in India, the smi code was incorrectly addressing the phy chip so it was never being programmed. The default register settings were good enough. 

David Norman
Bristol
